name: Build libraries for Blender

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  opencloudos:
    name: Build libraries for Blender on OpenCloudOS 9
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ github.workspace }}/ws_root

      - name: Checkout Blender repo
        run: |
          git-lfs install
          git clone -b loong64-port https://projects.blender.org/Yuanzhen-Gan/blender.git ${{ github.workspace }}/ws_root/blender

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/ws_root/build_linux/deps_loongarch64
          key: blender_build_deps_loongarch64-

      - name: Setup Cache
        run: |
          sudo mkdir -p ${{ github.workspace }}/ws_root/build_linux/deps_loongarch64
          sudo chown -R root:docker ${{ github.workspace }}/ws_root/build_linux/deps_loongarch64

      - name: Setup Docker
        run: |
          mkdir -p ${{ github.workspace }}/docker_data
          sudo systemctl stop docker.service
          sudo rm -f /etc/docker/daemon.json
          echo "{ \"data-root\": \"${{ github.workspace }}/docker_data\" }" | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker.service
          
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up container and build libs
        timeout-minutes: 330
        run: |
          DOCKER_IMAGE="ghcr.io/loong64/opencloudos:9"
          DOCKER_CMD=`cat << EOF
            set -e
            cd /work
            # Change mirror
            sed -i 's|mirrors\.opencloudos\.tech|mirrors.tencent.com|g' /etc/yum.repos.d/*.repo
            bash ./linux_opencloudos9_setup.sh 1>/dev/null
            yum clean all 1>/dev/null
            dnf clean all 1>/dev/null

            cd blender
            # Replace mirror
            # http://ftp.gnu.org/pub/gnu to https://ftpmirror.gnu.org/
            sed -i 's|http://ftp.gnu.org/pub/gnu|http://ftpmirror.gnu.org|g' build_files/build_environment/cmake/versions.cmake
            sed -i 's|https://gmplib.org/download|http://ftpmirror.gnu.org|g' build_files/build_environment/cmake/versions.cmake
            make deps
          EOF
          `
          docker run --rm \
            --cpus=`nproc` \
            --platform linux/loong64 \
            --volume /tmp/.cache:/root/.cache \
            --volume ${{ github.workspace }}/ws_root:/work \
            --workdir /work \
            "$DOCKER_IMAGE" \
            bash -c "$DOCKER_CMD"
            
      - name: Package built libraries
        run: |
          cd ${{ github.workspace }}/ws_root/blender/lib
          tar -czf linux_loongarch64.tar.gz linux_loongarch64
            
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build libraries for Blender on loong64
          path: ${{ github.workspace }}/ws_root/blender/lib/linux_loongarch64.tar.gz 
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`


      - name: Cache permissions
        if: always()
        run: |
          sudo chown -R runner:docker ${{ github.workspace }}/ws_root/build_linux/deps_loongarch64

      - name: Save Cache
        if: always()
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/ws_root/build_linux/deps_loongarch64
          key: blender_build_deps_loongarch64-${{ github.run_id }}
