name: Build libraries for Blender

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  opencloudos:
    name: Build libraries for Blender on OpenCloudOS 9
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 20480
          swap-size-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Blender repo
        run: |
          git-lfs install
          git clone -b loong64-port https://projects.blender.org/Yuanzhen-Gan/blender.git blender

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/build_linux/deps_loongarch64
          key: blender_build_deps_loongarch64-

      - name: Setup Cache
        run: |
          sudo mkdir -p ${{ github.workspace }}/build_linux/deps_loongarch64
          sudo chown -R root:docker ${{ github.workspace }}/build_linux/deps_loongarch64
          
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up loong64 Debian container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/loong64/opencloudos:9
          options: --cpus=4 --platform linux/loong64 --privileged -v ${{ github.workspace }}:/work
          run: |
            cd /work
            # Change mirror
            sed -i 's|mirrors\.opencloudos\.tech|mirrors.tencent.com|g' /etc/yum.repos.d/*.repo
            bash ./linux_opencloudos9_setup.sh
            yum clean all
            dnf clean all

            cd blender
            # Replace mirror
            # http://ftp.gnu.org/pub/gnu to https://ftpmirror.gnu.org/
            sed -i 's|http://ftp.gnu.org/pub/gnu|http://ftpmirror.gnu.org|g' build_files/build_environment/cmake/versions.cmake
            sed -i 's|https://gmplib.org/download|http://ftpmirror.gnu.org|g' build_files/build_environment/cmake/versions.cmake
            make deps
            
      - name: Package built libraries
        run: |
          cd blender/lib
          tar -czf linux_loongarch64.tar.gz linux_loongarch64
            
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build libraries for Blender on loong64
          path: ${{ github.workspace }}/blender/lib/linux_loongarch64.tar.gz 
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`


      - name: Cache permissions
        if: always()
        run: |
          sudo chown -R runner:docker ${{ github.workspace }}/build_linux/deps_loongarch64

      - name: Save Cache
        if: always()
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/build_linux/deps_loongarch64
          key: blender_build_deps_loongarch64-${{ github.run_id }}
