name: Build libraries for Blender

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  debian:
    name: Build loong64 iso image
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Blender repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: true
          repository: Yuanzhen-Gan/blender
          github-server-url: 'https://projects.blender.org'
          token: ''

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up loong64 Debian container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/loong64/opencloudos:9
          options: --cpus=4 --platform linux/loong64 --privileged -v ${{ github.workspace }}:/work
          run: |
            cd /work
            bash ./linux_opencloudos9_setup.sh
            
            cd blender
            make deps
            
            
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debian loong64 live cd ${{ matrix.variant }}
          path: ${{ github.workspace }}/blender/lib/linux_loongarch64/*
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
