name: Build libraries for Blender

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  debian:
    name: Build loong64 iso image
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8000
          swap-size-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up loong64 Debian container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/loong64/opencloudos:9
          options: --cpus=4 --platform linux/loong64 --privileged -v ${{ github.workspace }}:/work
          run: |
            cd /work
            bash ./linux_opencloudos9_setup.sh
            # Test ROCm
            /opt/rocm/bin/hipcc -v
            
            
      # - name: Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Debian loong64 live cd ${{ matrix.variant }}
      #     path: ${{ github.workspace }}/images/*.iso
      #     compression-level: 0
      #     if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
