name: Build libraries for Blender

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  debian:
    name: Build loong64 iso image
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Blender repo
        run: |
          git-lfs install
          git clone https://projects.blender.org/Yuanzhen-Gan/blender.git blender

      - uses: actions/cache@v4
        with:
          path: |
            build_linux/deps_loongarch64
          key: blender_build_deps_loongarch64
          restore-keys: blender_build_deps

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up loong64 Debian container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/loong64/opencloudos:9
          options: --cpus=4 --platform linux/loong64 --privileged -v ${{ github.workspace }}:/work
          run: |
            cd /work
            bash ./linux_opencloudos9_setup.sh
            
            cd blender
            # Replace mirror
            # http://ftp.gnu.org/pub/gnu to https://ftpmirror.gnu.org/
            sed -i 's|http://ftp.gnu.org/pub/gnu|http://ftpmirror.gnu.org|g' build_files/build_environment/cmake/versions.cmake
            sed -i 's|https://gmplib.org/download|http://ftpmirror.gnu.org|g' build_files/build_environment/cmake/versions.cmake
            make deps
            
      - name: Package built libraries
        run: |
          cd blender/lib
          tar -czf linux_loongarch64.tar.gz linux_loongarch64
            
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build libraries for Blender on loong64
          path: ${{ github.workspace }}/blender/lib/linux_loongarch64.tar.gz 
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
